Updated to newer openapi-generator-cli
ConsumerDataStandardsAustralia/standards-staging pull request #415
Opened 2024-07-25 04:26 UTC by nils-work

Added new jar and removed/replaced older jars.
Addresses https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/414

2024-09-11 02:28 UTC, abeheron1 approved these changes

2024-10-17 05:12 UTC, markverstege requested changes
Not approved until we review the Swagger file outputs and understand API contract impacts.

2024-10-17 07:43 UTC, nils-work commented
The newer version of the openapi-generator-cli (`openapi-generator-cli-6.6.0.jar`) provides recommendations in relation to the validity of the spec files that were not provided by the version used in previous builds.

Examples from build logs with previous version stating `No validation issues detected`: 
```
*** Input Swagger:  api/cds_dcr.json
*** Output Format:  openapi
*** Output Extension json
*** Output Dir: ../slate/source/includes/swagger
*** Checking OAS Validator ***
 No validation issues detected.spec (api/cds_dcr.json)
```

```
*** Input Swagger:  api/cds_telco.json
*** Output Format:  openapi
*** Output Extension json
*** Output Dir: ../slate/source/includes/swagger
*** Checking OAS Validator ***
 No validation issues detected.spec (api/cds_telco.json)
```

Examples from build logs with updated version stating `[info] Spec has ... recommendation(s)`: 
```
*** Input Swagger:  api/cds_dcr.json
*** Output Format:  openapi
*** Output Extension json
*** Output Dir: ../slate/source/includes/swagger
*** Checking OAS Validator ***
 [info] Spec has 1 recommendation(s).api/cds_dcr.json)
```
In the DCR spec., this recommendation appears to relate to the `ClientRegistration` definition being declared but not used (not directly referenced by an endpoint).

```
*** Input Swagger:  api/cds_telco.json
*** Output Format:  openapi
*** Output Extension json
*** Output Dir: ../slate/source/includes/swagger
*** Checking OAS Validator ***
 [info] Spec has 7 recommendation(s).tResponseontactson)
```
In the Telco spec., these recommendations appear to refer to unused definitions:
- `TelcoServiceUsageListResponse`
- `TelcoServiceDetail`
- `CommonPhysicalAddress`
- `TelcoAccountDetailAuthorisedContacts`

Validation of the OpenAPI spec. files early in the testing and build process helps to avoid redundant detail and errors at the final build stage.

2024-10-18 03:41 UTC, markverstege approved these changes

2024-10-18 03:50 UTC, HemangCDR approved these changes

2024-10-20 23:40 UTC, merged