Staging #410 - Update details in Common Field Types section
ConsumerDataStandardsAustralia/standards-staging pull request #420
Opened 2024-08-27 05:51 UTC by nils-work

Addresses: https://github.com/ConsumerDataStandardsAustralia/standards-staging/issues/410

2024-09-11 02:31 UTC, abeheron1 approved these changes

2024-10-10 06:35 UTC, HemangCDR approved these changes

2024-10-17 02:17 UTC, markverstege requested changes
Noting this change includes Requirement Level emphasis, whitespace and enhancements to other common field types that aren't listed in the Staging issue. These need to be reverted and included as a separate issue.

This change must only address improvements to RateString examples.

2024-10-18 03:41 UTC, markverstege approved these changes

2024-10-20 23:43 UTC, merged